Repository PhoenixDL/rising, pull requests merged in 2019-12, with the labels that each got.

#15 Codeowner
  .github/pull_request_template.md
  CODEOWNERS
Labels: FeatureRequest, ReadyForReview

#14 pypi release pipeline
  .github/workflows/pypi_release.yml
  .github/workflows/unittests.yml
Labels: ReadyForReview

#19 Readme badges0
  README.md
Labels: ReadyForReview

#16 Changelog
  .github/pull_request_template.md
  CHANGELOG.md
Labels: FeatureRequest, ReadyForReview

#6 Utility transforms
  rising/ops/tensor.py
  rising/transforms/__init__.py
  rising/transforms/abstract.py
  rising/transforms/channel.py
  rising/transforms/device.py
  rising/transforms/functional/__init__.py
  rising/transforms/functional/channel.py
  rising/transforms/functional/device.py
  rising/transforms/functional/tensor.py
  rising/transforms/functional/utility.py
  rising/transforms/intensity.py
  rising/transforms/kernel.py
  rising/transforms/spatial.py
  rising/transforms/utility.py
  tests/transforms/functional/test_channel.py
  tests/transforms/functional/test_device.py
  tests/transforms/functional/test_tensor.py
  tests/transforms/functional/test_utility.py
  tests/transforms/test_channel.py
  tests/transforms/test_compose.py
  tests/transforms/test_device.py
  tests/transforms/test_intensity_transforms.py
  tests/transforms/test_kernel_transforms.py
  tests/transforms/test_spatial_transforms.py
  tests/transforms/test_utility_transforms.py
Labels: ReadyForReview

#17 Add Contribution Guideline
  CONTRIBUTING.md
Labels: FeatureRequest, ReadyForReview

#20 convert fn for compose ,box to seg bug fix
  rising/loading/__init__.py
  rising/loading/loader.py
  rising/transforms/compose.py
  rising/transforms/functional/utility.py
  tests/transforms/functional/test_utility.py
Labels: Bug, FeatureRequest, ReadyForReview

#21 full multiprocessing support for cache data set
  requirements.txt
  rising/loading/dataset.py
  rising/transforms/compose.py
  tests/loading/test_dataset.py
Labels: Bug, ReadyForReview

#23 progressive resizing with multiprocessing
  rising/transforms/spatial.py
  tests/transforms/test_spatial_transforms.py
Labels: Bug, ReadyForReview
