Repository PhoenixDL/rising, pull requests merged in 2020-05, with the labels that each got.

#56 Google Docstrings
  .github/workflows/unittests_linux.yml
  .github/workflows/unittests_mac.yml
  .github/workflows/unittests_windows.yml
  requirements/install.txt
  requirements/install_async.txt
  rising/interface.py
  rising/loading/collate.py
  rising/loading/dataset.py
  rising/loading/loader.py
  rising/ops/tensor.py
  rising/transforms/abstract.py
  rising/transforms/affine.py
  rising/transforms/channel.py
  rising/transforms/compose.py
  rising/transforms/crop.py
  rising/transforms/format.py
  rising/transforms/functional/affine.py
  rising/transforms/functional/channel.py
  rising/transforms/functional/crop.py
  rising/transforms/functional/device.py
  rising/transforms/functional/intensity.py
  rising/transforms/functional/spatial.py
  rising/transforms/functional/tensor.py
  rising/transforms/functional/utility.py
  rising/transforms/intensity.py
  rising/transforms/kernel.py
  rising/transforms/spatial.py
  rising/transforms/tensor.py
  rising/transforms/utility.py
  rising/utils/affine.py
  rising/utils/checktype.py
  setup.py
  tests/transforms/test_compose.py
Labels: ReadyForReview

#61 Docs Setup
  .readthedocs.yml
  README.md
  docs/Makefile
  docs/_static/rising_Logo.png
  docs/_static/rising_logo.svg
  docs/build_docs.sh
  docs/make.bat
  docs/requirements.txt
  docs/source/_templates/layout.html
  docs/source/_templates/theme_variables.jinja
  docs/source/_templates_stable/layout.html
  docs/source/conf.py
  docs/source/getting_started.rst
  docs/source/images/logo/rising_icon.svg
  docs/source/images/logo/rising_logo.png
  docs/source/images/logo/rising_logo.svg
  docs/source/index.rst
  docs/source/loading.rst
  docs/source/ops.rst
  docs/source/transforms.functional.rst
  docs/source/transforms.rst
  docs/source/utils.rst
  rising/__init__.py
  rising/loading/__init__.py
  rising/loading/collate.py
  rising/loading/dataset.py
  rising/loading/loader.py
  rising/ops/__init__.py
  rising/ops/tensor.py
  rising/transforms/__init__.py
  rising/transforms/abstract.py
  rising/transforms/affine.py
  rising/transforms/channel.py
  rising/transforms/compose.py
  rising/transforms/functional/__init__.py
  rising/transforms/functional/affine.py
  rising/transforms/functional/channel.py
  rising/transforms/functional/spatial.py
  rising/transforms/functional/tensor.py
  rising/transforms/functional/utility.py
  rising/transforms/intensity.py
  rising/transforms/spatial.py
  rising/transforms/tensor.py
  rising/transforms/utility.py
  rising/utils/affine.py
  rising/utils/checktype.py
  setup.py
  tests/transforms/functional/test_spatial.py
  tests/transforms/test_spatial_transforms.py
Labels: FeatureRequest, ReadyForReview

#69 Doc pipeline
  .github/workflows/build_docs.yml
  .gitignore
  README.md
  docs/requirements.txt
  docs/source/conf.py
  docs/source/getting_started.rst
  docs/source/index.rst
  notebooks/transformations.ipynb
  rising/loading/collate.py
  rising/loading/dataset.py
  rising/loading/loader.py
  rising/ops/tensor.py
  rising/transforms/abstract.py
  rising/transforms/affine.py
  rising/transforms/compose.py
  rising/transforms/crop.py
  rising/transforms/format.py
  rising/transforms/functional/affine.py
  rising/transforms/functional/channel.py
  rising/transforms/functional/crop.py
  rising/transforms/functional/device.py
  rising/transforms/functional/intensity.py
  rising/transforms/functional/spatial.py
  rising/transforms/functional/tensor.py
  rising/transforms/functional/utility.py
  rising/transforms/intensity.py
  rising/transforms/kernel.py
  rising/transforms/spatial.py
  rising/transforms/tensor.py
  rising/transforms/utility.py
  rising/utils/affine.py
  rising/utils/checktype.py
Labels: FeatureRequest, WIP

#49 WIP: Random Parameter Injection
  docs/source/index.rst
  docs/source/random.rst
  docs/source/transforms.functional.rst
  docs/source/transforms.rst
  docs/source/utils.rst
  notebooks/external_augmentation.ipynb
  notebooks/transformations.ipynb
  rising/random/__init__.py
  rising/random/abstract.py
  rising/random/continuous.py
  rising/random/discrete.py
  rising/transforms/abstract.py
  rising/transforms/affine.py
  rising/transforms/compose.py
  rising/transforms/crop.py
  rising/transforms/format.py
  rising/transforms/functional/affine.py
  rising/transforms/functional/device.py
  rising/transforms/functional/intensity.py
  rising/transforms/functional/spatial.py
  rising/transforms/intensity.py
  rising/transforms/spatial.py
  rising/transforms/tensor.py
  rising/transforms/utility.py
  rising/utils/affine.py
  rising/utils/checktype.py
  rising/utils/shape.py
  tests/loading/test_loader.py
  tests/rand/__init__.py
  tests/rand/test_abstract.py
  tests/rand/test_continuous.py
  tests/rand/test_discrete.py
  tests/transforms/_utils.py
  tests/transforms/test_abstract_transform.py
  tests/transforms/test_affine.py
  tests/transforms/test_compose.py
  tests/transforms/test_crop.py
  tests/transforms/test_intensity_transforms.py
  tests/transforms/test_spatial_transforms.py
  tests/transforms/test_tensor.py
  tests/transforms/test_utility_transforms.py
  tests/utils/test_checktype.py
Labels: FeatureRequest, ReadyForReview, WIP

#75 Readme update
  README.md
  docs/source/images/dataloading/default.svg
  docs/source/images/dataloading/rising.svg
  rising/transforms/spatial.py
Labels: ReadyForReview

#78 Disable warnings for all workers but one
  CHANGELOG.md
  rising/loading/loader.py
Labels: FeatureRequest, ReadyForReview

#74 Lightning Segmentation example
  .github/workflows/notebook_tests_linux.yml
  .github/workflows/notebook_tests_mac.yml
  .github/workflows/unittests_linux.yml
  .github/workflows/unittests_mac.yml
  .github/workflows/unittests_windows.yml
  docs/source/tutorials.rst
  notebooks/lightning_segmentation.ipynb
  requirements/install.txt
  requirements/notebooks.txt
Labels: FeatureRequest, ReadyForReview

#80 Behavior fixes
  docs/source/random.rst
  rising/random/__init__.py
  rising/random/discrete.py
  rising/transforms/functional/intensity.py
  rising/transforms/intensity.py
  rising/transforms/spatial.py
  tests/rand/test_discrete.py
  tests/transforms/functional/test_intensity.py
  tests/transforms/test_spatial_transforms.py
Labels: ReadyForReview

#82 Additional transforms
  CHANGELOG.md
  docs/source/transforms.functional.rst
  docs/source/transforms.rst
  rising/transforms/channel.py
  rising/transforms/compose.py
  rising/transforms/format.py
  rising/transforms/functional/__init__.py
  rising/transforms/functional/channel.py
  rising/transforms/functional/device.py
  rising/transforms/functional/tensor.py
  tests/transforms/functional/test_channel.py
  tests/transforms/functional/test_device.py
  tests/transforms/test_channel.py
  tests/transforms/test_compose.py
  tests/transforms/test_format_transforms.py
Labels: ReadyForReview

#83 add per sample option for affine transforms
  CHANGELOG.md
  rising/transforms/affine.py
  tests/transforms/test_affine.py
Labels: ReadyForReview

#97 add dummy data
  notebooks/lightning_segmentation.ipynb
Labels: ReadyForReview

#81 Getting Started
  .github/workflows/build_docs.yml
  README.md
  docs/requirements.txt
  docs/source/conf.py
  docs/source/images/dataloading/default.png
  docs/source/images/dataloading/rising.png
  rising/loading/loader.py
Labels: ReadyForReview

#79 Cls example
  docs/source/tutorials.rst
  notebooks/classification_2d_mednist.ipynb
Labels: ReadyForReview

#101 fix download of mednist
  notebooks/classification_2d_mednist.ipynb
Labels: ReadyForReview

#100 Add BaseTransformSeeded and warnings to other transforms
  docs/source/transforms.rst
  rising/transforms/abstract.py
  rising/transforms/crop.py
  rising/transforms/functional/crop.py
  rising/transforms/intensity.py
  tests/transforms/functional/test_crop.py
  tests/transforms/test_crop.py
Labels: Bug, ReadyForReview
